.

diff --git a/git-pull b/git-pull
--- a/git-pull
+++ b/git-pull
@@ -1,5 +1,30 @@
 cd `dirname $0`
 
+echo " make sure you have installed the required dependencies "
+
+# first install a require script
+if ! [[ -x "$(command -v require.sh)" ]] ; then
+
+        echo " we need sudo to install require.sh to /usr/local/bin "
+        sudo wget -O /usr/local/bin/require.sh https://raw.githubusercontent.com/xriss/require.sh/main/require.sh
+        sudo chmod +x /usr/local/bin/require.sh
+
+fi
+
+# commands
+
+echo " some of these may fail and yet things may still work because racecar "
+
+require.sh qemu-system
+require.sh qemu-img
+require.sh /usr/bin/qemu-system-aarch64
+require.sh sshpass
+require.sh unzip
+require.sh gzip
+require.sh pv
+
+
+echo " checking out git is set up correctly"
 git pull --all
 git checkout main
 
@@ -12,4 +37,10 @@ if [ -d box ]; then
   git switch -c box
   cd ..
 fi
- git switch main
+git switch main
+
+echo " unpacking box img "
+cd build/debian11-arm64
+ln -s ../../box/debian11-arm64 box
+box/ungzip
+cd ../..
